'use client'

import { useState } from 'react'
import Card from '@/components/ui/Card'
import Button from '@/components/ui/Button'
import { Eye, Check, ArrowRight, RotateCcw, Star } from 'lucide-react'

const samples = [
  {
    id: 1,
    text: 'The old man the boats. The cotton clothing is made of grows in Mississippi.',
    isAI: false,
    source: 'Classic garden-path sentences used in linguistics research by Bever (1970)',
    difficulty: 'easy',
  },
  {
    id: 2,
    text: 'In the realm of artificial intelligence, large language models have emerged as powerful tools for natural language processing. These models, trained on vast corpora of text data, can generate human-like text, translate languages, and even write creative content. The underlying transformer architecture, introduced in the seminal "Attention Is All You Need" paper, utilizes self-attention mechanisms to capture long-range dependencies in sequential data.',
    isAI: true,
    source: 'Generated by GPT-4 when asked to explain LLMs in academic style',
    difficulty: 'medium',
  },
  {
    id: 3,
    text: 'I tried that new coffee place on 5th street yesterday. The latte was decent but honestly overpriced for what you get. $7 for something that basically tasted like Starbucks? Pass. The vibes were nice though, good study spot if you can handle the noise from the construction next door.',
    isAI: false,
    source: 'Reddit comment from r/localfood, 2024',
    difficulty: 'medium',
  },
  {
    id: 4,
    text: 'The proliferation of artificial intelligence technologies in educational settings presents both promising opportunities and significant challenges. As institutions increasingly integrate AI-powered tools into their curricula, educators must navigate complex ethical considerations while leveraging these innovations to enhance learning outcomes for diverse student populations.',
    isAI: true,
    source: 'Generated by Claude when asked to write an academic paragraph about AI in education',
    difficulty: 'hard',
  },
  {
    id: 5,
    text: 'my cat just knocked over my entire coffee onto my keyboard and now the spacebar only works if i slam it like im angry. thanks sir whiskers you absolute menace. anyone know if rice actually works for laptops or is that just a phone thing',
    isAI: false,
    source: 'Twitter/X post, authentic user complaint',
    difficulty: 'easy',
  },
  {
    id: 6,
    text: 'The Mediterranean diet, rich in olive oil, lean proteins, and fresh vegetables, has been consistently linked to improved cardiovascular health outcomes. Recent longitudinal studies spanning over two decades have demonstrated significant reductions in heart disease, stroke, and metabolic syndrome among adherents to this dietary pattern.',
    isAI: true,
    source: 'Generated by Gemini when asked to summarize Mediterranean diet research',
    difficulty: 'hard',
  },
]

export default function AIvsHumanPage() {
  const [currentIdx, setCurrentIdx] = useState(0)
  const [guess, setGuess] = useState<boolean | null>(null)
  const [score, setScore] = useState(0)
  const [completed, setCompleted] = useState(0)

  const sample = samples[currentIdx]
  const isFinished = completed >= samples.length

  const handleGuess = (guessedAI: boolean) => {
    setGuess(guessedAI)
    if (guessedAI === sample.isAI) {
      setScore((s) => s + 1)
    }
    setCompleted((c) => c + 1)
  }

  const handleNext = () => {
    if (currentIdx < samples.length - 1) {
      setCurrentIdx((i) => i + 1)
      setGuess(null)
    }
  }

  const handleRestart = () => {
    setCurrentIdx(0)
    setGuess(null)
    setScore(0)
    setCompleted(0)
  }

  return (
    <div className="p-6 md:p-8 max-w-3xl mx-auto">
      <div className="animate-fade-in mb-8">
        <h1 className="text-3xl font-bold text-text-primary mb-2">AI vs Human Text</h1>
        <p className="text-text-secondary">Can you tell which text was written by AI and which by a human?</p>
      </div>

      {/* Score */}
      <Card padding="sm" className="mb-6">
        <div className="flex items-center justify-between">
          <span className="text-sm text-text-secondary">Score: {score}/{completed}</span>
          <span className="text-sm text-text-muted">{currentIdx + 1}/{samples.length}</span>
        </div>
        <div className="flex gap-1 mt-2">
          {samples.map((_, i) => (
            <div key={i} className={`flex-1 h-1.5 rounded-full transition-colors ${
              i < completed ? (i < score ? 'bg-green' : 'bg-red') : i === currentIdx ? 'bg-accent' : 'bg-border-subtle'
            }`} />
          ))}
        </div>
      </Card>

      {!isFinished && (
          <div key={sample.id} className="animate-fade-in">
            <Card padding="lg" className="mb-6">
              <div className="flex items-center gap-2 mb-4">
                <Eye size={18} className="text-accent" />
                <span className={`text-xs px-2 py-0.5 rounded-full ${
                  sample.difficulty === 'easy' ? 'bg-green/10 text-green' : sample.difficulty === 'medium' ? 'bg-gold/10 text-gold' : 'bg-red/10 text-red'
                }`}>{sample.difficulty}</span>
              </div>

              <div className="p-4 rounded-xl bg-surface-raised border border-border-subtle mb-6">
                <p className="text-sm text-text-primary leading-relaxed">{sample.text}</p>
              </div>

              {guess === null ? (
                <div className="flex gap-3">
                  <Button onClick={() => handleGuess(true)} variant="secondary" className="flex-1">🤖 AI Generated</Button>
                  <Button onClick={() => handleGuess(false)} variant="secondary" className="flex-1">✍️ Human Written</Button>
                </div>
              ) : (
                <div className="animate-fade-in">
                  <div className={`p-4 rounded-xl mb-4 ${guess === sample.isAI ? 'bg-green/10 border border-green/20' : 'bg-red/10 border border-red/20'}`}>
                    <p className="text-sm font-semibold mb-1">{guess === sample.isAI ? '✅ Correct!' : '❌ Wrong!'}</p>
                    <p className="text-sm text-text-secondary mb-2">
                      This was <strong>{sample.isAI ? '🤖 AI-generated' : '✍️ human-written'}</strong>.
                    </p>
                    <p className="text-xs text-text-muted">Source: {sample.source}</p>
                  </div>
                  {currentIdx < samples.length - 1 && (
                    <Button onClick={handleNext} icon={<ArrowRight size={16} />}>Next</Button>
                  )}
                </div>
              )}
            </Card>
          </div>
      )}

      {isFinished && (
        <div className="animate-bounce-in">
          <Card padding="lg" glow className="text-center">
            <Star size={40} className="text-gold mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-text-primary mb-2">Quiz Complete!</h2>
            <p className="text-4xl font-bold text-accent mb-2">{score}/{samples.length}</p>
            <p className="text-text-secondary mb-4">
              {score === samples.length ? '🏆 Perfect! You\'re an AI text detection expert!' :
               score >= samples.length * 0.7 ? '🎉 Great eye! You can spot AI text well.' :
               score >= samples.length * 0.5 ? '👍 Not bad! AI text is getting harder to spot.' :
               '🤔 AI text fooled you — that\'s the point! It\'s getting harder to tell.'}
            </p>
            <Button onClick={handleRestart} icon={<RotateCcw size={16} />}>Try Again</Button>
          </Card>
        </div>
      )}
    </div>
  )
}
